"""create event table

Revision ID: ef13b2e35c6a
Revises: 3477c732ad6a
Create Date: 2024-12-04 09:41:18.667507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef13b2e35c6a'
down_revision: Union[str, None] = '3477c732ad6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('dvr_id', sa.Integer(), nullable=False),
    sa.Column('camera', sa.String(length=30), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dvr_id'], ['dvrs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
