"""create_city_and_chat_table

Revision ID: c5bcf637b06d
Revises: ef13b2e35c6a
Create Date: 2024-12-18 12:35:22.767761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bcf637b06d'
down_revision: Union[str, None] = 'ef13b2e35c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('tg_chat_id', sa.Integer(), nullable=False),
    sa.Column('hdd_error', sa.Integer(), nullable=False),
    sa.Column('view_tampering', sa.Integer(), nullable=False),
    sa.Column('video_signal_lost', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('chats')
    # ### end Alembic commands ###
