"""change_tg_chat_id_type_to_b_int

Revision ID: e3e58551c662
Revises: c5bcf637b06d
Create Date: 2024-12-18 15:17:08.903739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e3e58551c662"
down_revision: Union[str, None] = "c5bcf637b06d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats",
        "tg_chat_id",
        existing_type=mysql.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats",
        "tg_chat_id",
        existing_type=sa.BigInteger(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
