"""create relation with dvrs and cities table

Revision ID: dc6a584e942c
Revises: 64a2e4693f1a
Create Date: 2024-12-24 15:53:45.318078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6a584e942c'
down_revision: Union[str, None] = '64a2e4693f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dvrs', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dvrs', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dvrs', type_='foreignkey')
    op.drop_column('dvrs', 'city_id')
    # ### end Alembic commands ###
