"""add colume name to city table

Revision ID: fe91d6273c17
Revises: dc6a584e942c
Create Date: 2024-12-24 21:15:10.093151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe91d6273c17"
down_revision: Union[str, None] = "dc6a584e942c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("name", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "name")
    # ### end Alembic commands ###
