"""add updates

Revision ID: c293caa7ac89
Revises: fe91d6273c17
Create Date: 2025-03-20 10:16:41.843591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c293caa7ac89'
down_revision: Union[str, None] = 'fe91d6273c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dvrs', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dvrs', 'divisions', ['division_id'], ['id'])
    op.drop_column('dvrs', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dvrs', sa.Column('city', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'dvrs', type_='foreignkey')
    op.drop_column('dvrs', 'division_id')
    op.drop_table('divisions')
    # ### end Alembic commands ###
