"""add stat field to chat tbl

Revision ID: 500a57bfca8b
Revises: 0af672921040
Create Date: 2025-03-21 09:50:33.521724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500a57bfca8b'
down_revision: Union[str, None] = '0af672921040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('statistic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'statistic')
    # ### end Alembic commands ###
