"""add updates mo

Revision ID: 28b4cf161d08
Revises: c293caa7ac89
Create Date: 2025-03-20 10:54:27.416061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "28b4cf161d08"
down_revision: Union[str, None] = "c293caa7ac89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cities", "chat_id", existing_type=mysql.INTEGER(), nullable=True)
    op.add_column("divisions", sa.Column("chat_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "divisions", "chats", ["chat_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "divisions", type_="foreignkey")
    op.drop_column("divisions", "chat_id")
    op.alter_column("cities", "chat_id", existing_type=mysql.INTEGER(), nullable=False)
    # ### end Alembic commands ###
