"""add updates mo

Revision ID: 045036672abb
Revises: 28b4cf161d08
Create Date: 2025-03-20 12:48:44.998088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '045036672abb'
down_revision: Union[str, None] = '28b4cf161d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cities_ibfk_1', 'cities', type_='foreignkey')
    op.drop_column('cities', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cities_ibfk_1', 'cities', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
