"""add updates

Revision ID: 0af672921040
Revises: 045036672abb
Create Date: 2025-03-20 13:23:01.608687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0af672921040'
down_revision: Union[str, None] = '045036672abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dvrs_ibfk_1', 'dvrs', type_='foreignkey')
    op.drop_column('dvrs', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dvrs', sa.Column('city_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dvrs_ibfk_1', 'dvrs', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
